### ISSUE TITLE
client and pure API params are not consistent

### ISSUE THREAD

**Issue by quarryman** [gonebusy/gonebusy-nodejs-client#10]
According to API docs http://sandbox.gonebusy.com/docs/api_sandbox#!/services/get_service_available_slots_by_id
pure API method specified above expects params to be passed as object with next keys

```js
{
  date: '2017-01-01', // we omit this key in our particular case
  start_date: '2017-01-01',
  end_date: '2017-01-02'
}
```

It generates request to 
http://sandbox.gonebusy.com/api/v1/services/197264885/available_slots?start_date=2014-01-01&end_date=2014-01-03

and it works fine (we get 200 response)

Code trying to reproduce the same request using nodejs-client

```
import gonebusy from 'gonebusy-nodejs-client/lib';
import { Promise } from 'bluebird';

// promisifying requests using bluebird according to docs
const ServicesController = Promise.promisifyAll(gonebusy.ServicesController);

const config = {
  baseUri: 'http://sandbox.gonebusy.com/api/v1'
};

//running request to API that must return promise
ServicesController.getServiceAvailableSlotsByIdAsync({
      authorization: sample_token,
      id: 197264885, //one used with curl API request
      start_date: '2014-01-01',
      end_date: '2014-01-03'
    })
```

Here the problems start
1. In browser network tab we see next request details

```
Request URL:http://sandbox.gonebusy.com/api/v1/services/7891245607/available_slots?

Request Method:GET

Status Code:400 Bad Request
```

Response is 
`{"message":"Bad Request - Missing date params"}`

Client didnt send start and end dates in params as can be seen from Request URL: http://sandbox.gonebusy.com/api/v1/services/7891245607/available_slots?
and server validation failed respectively.

Sources tell that client expects hash keys to be in camelCase according to
https://github.com/gonebusy/gonebusy-nodejs-client/blob/master/lib/Controllers/ServicesController.js#L419

So we must pass it like that 

```
ServicesController.getServiceAvailableSlotsByIdAsync({
      authorization: sample_token,
      id: 197264885, //one used with curl API request
      startDate: '2014-01-01', // camelCase
      endDate: '2014-01-03' // camelCase
    })
```

and it works as expected then.

So client accepts keys in camelCase and transforms to the format that pure API expects to receive.
This should be documented and might also apply to other controllers.

2. Another annoying thing is that though validation error can be seen in responce itself, bluebird logs its own console error, much less verbose and that is the one that you see first, before you may try looking at request itself.
Bluebird, that i suspect to be this error logger, logs it like this

`Unhandled rejection (<{"errorMessage":"Bad Request","errorCo...>, no stack trace)`

This means bluebird wrapping doesn't not handle some errors correctly and needs further investigation.

3. If we use underscore in params object keys, nodejs client just doesnt send those params to API and we get missing params validation error. However if we pass only one of 2 required params (startDate or endDate) correctly, API behaviour is inconsistent and it responds with html instead of json.

This can be reproduced by using next curt

`curl -X GET --header 'Accept: text/html' --header 'Authorization: Token ac98ed08b5b0a9e7c43a233aeba841ce' 'http://sandbox.gonebusy.com/api/v1/services/197264885/available_slots?end_date=2014-01-03'
`

I am not providing html response here, but shortly it's gonebusy website html.

**Comment by alexagranov** [comment]
hi @quarryman Thank you for the in-depth issue report, this is really helpful to identify initial roadblocks for users.  Let me try to address each one of your points:

1. Yes, you are absolutely correct I should have provided some more documentation about how to use the Request Body helpers.  The camelCase vs. snake_case issue is very common with Node apps as Node/ES6 prefer camelCase but the backend API uses snake_case (GB has chosen snake_case for the API).  

For this scenario, the Body helper objects provide for the consistent use of snake_case params as follows:

```js
new_service = new CreateServiceBody({
    name: 'My Sample Service',
    duration: 30,
    description: 'Sample Service for Testing',
    short_name: 'MyService'
});

services.createServiceAsync({
    authorization: 'Token ac98ed08b5b0a9e7c43a233aeba841ce',
    createServiceBody: new_service
}).then((result)=>{console.log(result);});
```

Note how `short_name` was provided as a property to the constructor for CreateServiceBody.  I'll add to the Readme to show this example usage right after this.

2. I'll have to investigate further to see how Bluebird is wrapping the error but can we just always default to inspecting error on the response itself?

3. I believe you should have more success using snake_case params if you follow the pattern in 1) above (and forthcoming Readme update).

But as for providing only `end_date` with no other params and getting a 500 from the server, you've found a :bug:!!!  Looks like we missed a validation for that scenario.  I'll be patching shortly and update you offline.

Let me know if you have any other questions and great job!

**Comment by quarryman** [comment]
I believe after BodeHelpers examples has been added to docs, we can close the issue.
