### ISSUE TITLE
BookingsController.createBooking possibly wouldn't send request params passed to it.

### ISSUE THREAD

**Issue by quarryman** [gonebusy/gonebusy-nodejs-client#12]
Hi.
The code example below is expected to create new booking according to docs.
Providing valuable part only and omiting imports and promosification.

```
const authorization = "Token xxx";
const createBookingBody = new CreateBookingBody({
  service_id: 7891245607,    //real service ID
  date: '2017-01-14',
  time: '11:30',
  duration: 30                        //can be removed without affecting responce
});

BookingsController
  .createBookingAsync({ authorization, createBookingBody })
  .then(response => { console.log('creating booking: ', response); });
```

Request responds with:

`422 {"message":"422 Unprocessable Entity - Validation failed: Size cannot be zero"}`

If I look at request details  request body is not sent to API that's why I blame client in this scenario.
Sending params without BodyHelper won't change anything.

**Comment by alexagranov** [comment]
Hi @quarryman,

The client is fine.  The returned 422 is a red-herring: somehow you created a Service with `duration=0` which is not allowed but appears to be a bug.  

I've amended the Service to have `duration=30` and just successfully booked for 11:30 EST.

Let me know if you have another issue with this Service.

Thanks for debugging! :-)

**Comment by quarryman** [comment]
It should be considered fixed as I can book now.
Thanx for being very responsive.
Closing
